export const SELECT_TICKET = 'SELECT_TICKET';
export const GET_SESSIONS_SUCCESS = 'GET_SESSIONS_SUCCESS';
export const GET_SESSIONS_FAILURE = 'GET_SESSIONS_FAILURE';
export const GET_ADDITIONAL_SERVICES_SUCCESS = 'GET_ADDITIONAL_SERVICES_SUCCESS';
export const GET_ADDITIONAL_SERVICES_FAILURE = 'GET_ADDITIONAL_SERVICES_FAILURE';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAILURE = 'GET_MOVIES_FAILURE';
export const GET_CINEMAS_SUCCESS = 'GET_CINEMAS_SUCCESS';
export const GET_CINEMAS_FAILURE = 'GET_CINEMAS_FAILURE';

