export const GET_HALL_SUCCESS = 'GET_HALL_SUCCESS';
export const GET_HALL = 'GET_HALL';

export const GET_SESSIONS = 'GET_SESSIONS';
export const GET_SESSIONS_SUCCESS = 'GET_SESSIONS_SUCCESS';
export const GET_SESSIONS_FAILURE = 'GET_SESSIONS_FAILURE';

export const GET_ADDITIONAL_SERVICES = 'GET_ADDITIONAL_SERVICES';
export const GET_ADDITIONAL_SERVICES_SUCCESS = 'GET_ADDITIONAL_SERVICES_SUCCESS';
export const GET_ADDITIONAL_SERVICES_FAILURE = 'GET_ADDITIONAL_SERVICES_FAILURE';

export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIE = 'GET_MOVIE';
export const GET_MOVIES = 'GET_MOVIES';
export const GET_MOVIES_FAILURE = 'GET_MOVIES_FAILURE';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const FILTER_MOVIES_SUCCESS = 'FILTER_MOVIES_SUCCESS';


export const GET_CINEMA = 'GET_CINEMA';
export const GET_CINEMAS = 'GET_CINEMAS';
export const GET_CINEMAS_SUCCESS = 'GET_CINEMAS_SUCCESS';
export const GET_CINEMA_SUCCESS = 'GET_CINEMA_SUCCESS';
export const GET_CINEMAS_FAILURE = 'GET_CINEMAS_FAILURE';

export const BUY_TICKETS = 'BUY_TICKETS';
export const BUY_TICKETS_SUCCESS = 'BUY_TICKETS_SUCCESS';
export const GET_BOUGHT_TICKETS = 'GET_BOUGHT_TICKETS';
export const GET_BOUGHT_TICKETS_SUCCESS = 'GET_BOUGHT_TICKETS_SUCCESS';
export const ADD_BOUGHT_TICKET = 'ADD_BOUGHT_TICKET';

export const CLEAR_SELECTED_LIST = 'CLEAR_SELECTED_LIST';
export const CLEAR_BOOKING = 'CLEAR_BOOKING';


export const GET_SEATS = 'GET_SEATS';
export const GET_SEATS_SUCCESS = 'GET_SEATS_SUCCESS';
export const GET_SEATS_FAILURE = 'GET_SEATS_FAILURE';
export const GET_SELECTED_SEATS = 'GET_SELECTED_SEATS';
export const GET_SELECTED_SEATS_SUCCESS = 'GET_SELECTED_SEATS_SUCCESS';
export const ADD_SELECTED_SEAT = 'ADD_SELECTED_SEAT';
export const TOGGLE_SEAT_SUCCESS = 'TOGGLE_SEAT_SUCCESS';
export const TOGGLE_SEAT = 'TOGGLE_SEAT';


export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const CHECK_AUTH = 'CHECK_AUTH';
export const CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS';

export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR';

export const SHOW_SPINNER = 'SHOW_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';
